@resource = orders

// My Api
### Obtener órdenes
GET {{apiUrl}}/{{resource}}
    &limit=3
    &offset=3
Authorization: {{token}}

// ML Api

### Obtener órdenes
GET {{apiUrlMl}}/{{resource}}/search
    ?seller=166877629
    &sort=date_desc
    &limit=3
    &offset=3
Authorization: {{token}}

### Obtener orden
GET {{apiUrlMl}}/{{resource}}/5397749808
Authorization: {{token}}