@resource = orders

// My Api
### Obtener órdenes
GET http://localhost:3010/api/orders?page=1
Authorization: APP_USR-8756892310430960-041704-5a371de153b318ee6b7858557421b77f-166877629

// ML Api

### Obtener órdenes
GET {{apiUrlMl}}/{{resource}}/search
    ?seller=166877629
    &sort=date_desc
    &limit=3
    &offset=3
Authorization: {{token}}

### Obtener orden
GET {{apiUrlMl}}/{{resource}}/5397749808
Authorization: {{token}}