### Obtener productos
GET https://api.mercadolibre.com/sites/MCO/search?seller_id=166877629&without_stock=true

### Obtener productos
https://api.mercadolibre.com/users/166877629/items/search?status=paused
Authorization: Bearer APP_USR-8756892310430960-053017-9bc8944497c7d3ea82f6e4110e51f385-166877629

### Obtener producto
GET https://api.mercadolibre.com/items?ids=MCO832935783&attributes=id,title,price,base_price,original_price,available_quantity,
Authorization: Bearer APP_USR-1425564282392279-101512-4a8b4fcbc760d68d30e8ab53e91341ba-166877629

### Obtener producto por SKU
GET https://api.mercadolibre.com/users/166877629/items/search?seller_sku=CAM1
Authorization: Bearer APP_USR-1425564282392279-101512-4a8b4fcbc760d68d30e8ab53e91341ba-166877629

@categoryId = 
### Obtener ítems listados en una categoría
GET {{apiUrlMl}}/sites/{{siteId}}/search?category=$CATEGORY_ID


// My api

### Obtener producto
GET http://localhost:3010/api/items/MCO401912



// Linio
### Crear producto
POST https://sellercenter-api.linio.com.mx/?Action=ProductCreate&Format=JSON&UserID=CO5YUF0&Version=1.0&Signature=b221d9dbb083a7f33428d7c2a3c3198ae925614d70210e28716ccaa7cd4ddb79

### Obtener productos
GET https://sellercenter-api.linio.com.co/?Action=GetProducts&Timestamp=2022-05-05T02:14:53.174Z&UserID=CO5YUF0&Version=1.0&Signature=h5dQsM0EVvIge9UTE5NC7kvifF9cShRXGva0qgd0fUo=