### Obtener productos
GET https://api.mercadolibre.com/sites/MCO/search?seller_id=166877629&without_stock=true

### Obtener productos
https://api.mercadolibre.com/users/166877629/items/search?status=paused
Authorization: Bearer APP_USR-8756892310430960-053017-9bc8944497c7d3ea82f6e4110e51f385-166877629

### Obtener producto
GET https://api.mercadolibre.com/items/MCO652717196
Authorization: Bearer APP_USR-8756892310430960-042422-39dec71d79c8a890f0e96967e780f857-166877629

@categoryId = 
### Obtener ítems listados en una categoría
GET {{apiUrlMl}}/sites/{{siteId}}/search?category=$CATEGORY_ID


// My api

### Obtener producto
GET http://localhost:3010/api/items/MCO401912



// Linio
### Crear producto
POST https://sellercenter-api.linio.com.mx/?Action=ProductCreate&Format=JSON&UserID=CO5YUF0&Version=1.0&Signature
